name: Build and Release CLI App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'start.py'
          python_ver: '3.10.11'
          upload_exe_with_name: 'BlumClicker'
          options: '--onefile, --icon "app.ico", --name "Blum Clicker"'
