name: Build and Release CLI App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build CLI App
        run: |
          pyinstaller --onefile --icon=app.ico --name=blum-clicker start.py

      - name: Upload to Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/blum-clicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
